name: Generate PDF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install mdBook
        run: |
            mkdir bin
            curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.30/mdbook-v0.4.30-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
            echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Build book
        run: mdbook build

      - name: Install wkhtmltopdf
        run: sudo apt-get update && sudo apt-get install -y wkhtmltopdf

      - name: Setup for PDF generation
        run: |
          # Create a list of all HTML files in the correct order
          cat src/SUMMARY.md | grep -o "\(\.\/.*\.md\)" | sed 's/\.md$/\.html/' > pages.txt
          # Create a temp file to combine all pages
          echo '<html><head>
            <link rel="stylesheet" href="book.css">
            <script src="mermaid.min.js"></script>
            <script>
              document.addEventListener("DOMContentLoaded", function() {
                if (typeof mermaid !== "undefined") {
                  mermaid.initialize({
                    startOnLoad: true,
                    theme: "dark",
                    themeVariables: {
                      primaryColor: "#2b79a2",
                      primaryTextColor: "#c8c9db",
                      primaryBorderColor: "#3b3f51",
                      lineColor: "#c8c9db",
                      secondaryColor: "#272935",
                      tertiaryColor: "#161923"
                    }
                  });
                  
                  // Force re-initialization after a small delay to ensure diagrams render
                  setTimeout(function() {
                    mermaid.init(undefined, document.querySelectorAll(".mermaid"));
                  }, 1000);
                }
              });
            </script>
          </head><body class="navy no-js">' > combined.html
          
          # Add Navy theme CSS overrides
          echo "<style>
            @page {
              margin: 0;
              size: A4;
            }
            html { 
              background-color: #161923 !important;
            }
            html.navy, body.navy {
              background-color: #161923 !important;
              color: #c8c9db !important;
            }
            body {
              background-color: #161923 !important;
              color: #c8c9db !important;
              margin: 0;
              padding: 0;
            }
            .chapter {
              background-color: #161923 !important;
              color: #c8c9db !important;
              padding: 1em;
            }
            pre, code {
              background-color: #272935 !important;
              border-color: #3b3f51 !important;
            }
            a, a:hover {
              color: #2b79a2 !important;
            }
            /* Additional overrides for navy theme elements */
            .header, .sidebar, .content, .footer {
              background-color: #161923 !important;
              color: #c8c9db !important;
            }
            table, th, td {
              border-color: #3b3f51 !important;
            }
            th, h1, h2, h3, h4, h5, h6 {
              color: #ffffff !important;
            }
            blockquote {
              border-color: #3b3f51 !important;
              background-color: #272935 !important;
              color: #c8c9db !important;
            }
            /* Override any white backgrounds */
            * {
              border-color: #3b3f51 !important;
            }
            /* Fix for potential white border issue */
            #content {
              margin: 0 !important;
              max-width: 100% !important;
              padding: 0 !important;
              background-color: #161923 !important;
            }
            .page {
              background-color: #161923 !important;
              box-shadow: none !important;
              margin: 0 !important;
              padding: 1em !important;
              border: none !important;
            }
            /* Add matching 10pt border wrapper */
            .pdf-wrapper {
              background-color: #161923;
              padding: 10pt;
              box-sizing: border-box;
              width: 100%;
              min-height: 100vh;
            }
            /* Ensure content container has matching background */
            .pdf-content {
              background-color: #161923;
              color: #c8c9db;
              padding: 1em;
            }
            /* Mermaid styling */
            .mermaid {
              background-color: #161923 !important;
            }
            .mermaid .label {
              color: #c8c9db !important;
            }
            .mermaid .node rect, .mermaid .node circle, .mermaid .node ellipse, .mermaid .node polygon, .mermaid .node path {
              fill: #272935 !important;
              stroke: #3b3f51 !important;
            }
          </style>" >> combined.html
          
          # Loop through each page and append its content with wrapper for border
          echo "<div class='pdf-wrapper'><div class='pdf-content'>" >> combined.html
          while read page; do
            # Extract the main content from each page and append it
            page_path="book/${page}"
            echo "<div class='chapter'>" >> combined.html
            # Extract the content between <main> tags
            awk -v RS='<main[^>]*>' 'NR>1{sub(/<\/main>.*/,"");print}' "$page_path" >> combined.html
            echo "</div>" >> combined.html
          done < pages.txt
          echo "</div></div></body></html>" >> combined.html
          
          # Copy stylesheets and JS files to ensure formatting is preserved
          cp book/*.css .
          cp book/*.js .
          cp -r book/css .
          # Make sure to copy the mermaid JS files if they're in a different location
          [ -d "book/js" ] && cp -r book/js .

      - name: Generate PDF
        run: |
          wkhtmltopdf \
            --enable-local-file-access \
            --javascript-delay 5000 \
            --no-stop-slow-scripts \
            --outline \
            --outline-depth 3 \
            --footer-right '[page]/[topage]' \
            --footer-font-size 8 \
            --footer-line \
            --margin-top 10 \
            --margin-bottom 10 \
            --margin-left 10 \
            --margin-right 10 \
            --user-style-sheet css/general.css \
            --user-style-sheet css/variables.css \
            --user-style-sheet css/navy.css \
            --user-style-sheet css/navy-highlight.css \
            --print-media-type \
            --background \
            combined.html \
            presentation.pdf

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: presentation-pdf
          path: presentation.pdf