name: Generate PDF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install mdBook
        run: |
            mkdir bin
            curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.30/mdbook-v0.4.30-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
            echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Build book
        run: mdbook build

      - name: Install wkhtmltopdf
        run: sudo apt-get update && sudo apt-get install -y wkhtmltopdf

      - name: Setup for PDF generation
        run: |
          # Create a list of all HTML files in the correct order
          cat src/SUMMARY.md | grep -o "\(\.\/.*\.md\)" | sed 's/\.md$/\.html/' > pages.txt
          # Create a temp file to combine all pages
          echo "<html><head><link rel='stylesheet' href='book.css'></head><body>" > combined.html
          # Loop through each page and append its content
          while read page; do
            # Extract the main content from each page and append it
            page_path="book/${page}"
            echo "<div class='chapter'>" >> combined.html
            # Extract the content between <main> tags
            awk -v RS='<main[^>]*>' 'NR>1{sub(/<\/main>.*/,"");print}' "$page_path" >> combined.html
            echo "</div>" >> combined.html
          done < pages.txt
          echo "</body></html>" >> combined.html
          # Copy stylesheets to ensure formatting is preserved
          cp book/*.css .

      - name: Generate PDF
        run: |
          wkhtmltopdf \
            --enable-local-file-access \
            --javascript-delay 1000 \
            --no-stop-slow-scripts \
            --outline \
            --outline-depth 3 \
            --footer-right '[page]/[topage]' \
            --footer-font-size 8 \
            --footer-line \
            --margin-top 20 \
            --margin-bottom 20 \
            --margin-left 20 \
            --margin-right 20 \
            --user-style-sheet book/css/general.css \
            --user-style-sheet book/css/chrome.css \
            --user-style-sheet book/css/variables.css \
            combined.html \
            presentation.pdf

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: presentation-pdf
          path: presentation.pdf
